services:
  postgres:
    image: postgres:17
    container_name: ai_doc_qa_postgres
    environment:
      POSTGRES_USER: ai_doc_qa
      POSTGRES_PASSWORD: pg**ai**doc
      POSTGRES_DB: doc_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai_doc_qa_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: