name: Github Actions CI
run-name: ${{ gihub.actor }} is testing out GH Actions
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{gihub.event_name}} event."
      - run: echo "This job is currently running on a ${{runner.os}} server hosted on Github!"
      - run: echo "The name of my branch is ${{github.ref}} and repo is ${{gihub.repository}}."
      - name: Check out repo code
        uses: actions/checkout@v6
      - run: echo "the ${{gihub.repository}} repository has been cloned to the runner"
      - run: echo "the workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{github.workspace}}
      - run: echo "the job's status is ${{job.status}}"